// Bug happens on JS 
// FILE: tmp.kt

fun box()    =
try {} catch (e: Exception) {
{
    do 
                ({})
             while (true)
}
    }
